model:
  dropout: 0.5
  encoder_hidden_size: 256
  decoder_hidden_size: 256
  embedding_dim: 128
  num_layers: 2

training:
  batch_size: 2048
  epochs: 100
  lr: 1e-5
  weight_decay: 0.01
  note_loss_weight: 0.5
  duration_loss_weight: 0.3
  gap_loss_weight: 0.2
  print_predictions: False # print first eval predictions during training
  generate_temp: 0.6

data:
  data_dir: './data/data_aug_step20'
  max_sequence_length: 21 # include <eos>

seed: 42
out_dir: './runs/RNN'