model:
  model_name: 't5-small'
  dropout: 0.1
  expansion_factor: 1
  num_layers: 1
  num_heads: 8

training:
  batch_size: 128
  epochs: 2
  lr: 1e-5
  weight_decay: 0
  train_encoder: False
  note_loss_weight: 0.2
  duration_loss_weight: 0.1
  gap_loss_weight: 0.1


data:
  data_dir: './data/new_dataset'
  max_sequence_length: 200
  output_eos: 1
  use_syllables: False

seed: 42