model:
  model_name: 't5'
  note_loss_weight: 1.0
  duration_loss_weight: 1.0
  gap_loss_weight: 1.0

training:
  batch_size: 8
  epochs: 4
  lr: 1e-4

data:
  data_dir: './data/new_dataset'
  max_sequence_length: 512
  output_eos: [-1, -1, -1]
  use_syllables: False

seed: 42