model:
  model_name: 't5-small'
  dropout: 0.3
  expansion_factor: 4
  num_layers: 6
  num_heads: 8

training:
  batch_size: 352
  epochs: 50
  lr: 1e-4
  weight_decay: 0
  train_encoder: False
  note_loss_weight: 1.0
  duration_loss_weight: 1.0
  gap_loss_weight: 1.0


data:
  data_dir: './data/new_dataset'
  max_sequence_length: 20
  output_eos: 1
  use_syllables: False

seed: 42