model:
  dropout: 0.5
  encoder_hidden_size: 400
  decoder_hidden_size: 400
  embedding_dim: 128
  num_layers: 1

training:
  batch_size: 1024
  epochs: 200
  lr: 1e-5
  weight_decay: 0.01
  note_loss_weight: 0.6
  duration_loss_weight: 0.3
  gap_loss_weight: 0.1
  print_predictions: False # print first eval predictions during training
  generate_temp: 0.6

data:
  data_dir: './data/data_aug_step20'
  max_sequence_length: 21 # include <eos>

seed: 42
out_dir: './runs/RNN'