model:
  dropout: 0.5
  encoder_hidden_size: 512
  decoder_hidden_size: 512
  embedding_dim: 300
  num_layers: 16

training:
  batch_size: 256
  epochs: 50
  lr: 1e-4
  weight_decay: 0.01
  note_loss_weight: 0.6
  duration_loss_weight: 0.3
  gap_loss_weight: 0.1
  print_predictions: True # print first eval predictions during training

data:
  data_dir: './data/new_dataset_length20'
  max_sequence_length: 21 # include <eos>

seed: 42
out_dir: './runs/RNN'