model:
  model_name: 't5'
  note_loss_weight: 1.0
  duration_loss_weight: 1.0
  gap_loss_weight: 1.0

training:
  batch_size: 8
  epochs: 3
  lr: 1e-4

data:
  data_dir: './data/new_dataset'
  max_sequence_length: 512
  output_eos: [0, 0, 0]
  use_syllables: True

seed: 42