model:
  model_name: 't5'
  dropout: 0.2

training:
  batch_size: 300
  epochs: 4
  lr: 5e-5
  weight_decay: 0.01
  train_encoder: False
  note_loss_weight: 0.8
  duration_loss_weight: 0.5
  gap_loss_weight: 0.5


data:
  data_dir: './data/new_dataset'
  max_sequence_length: 200
  output_eos: 1
  use_syllables: False

seed: 42