model:
  model_name: 't5'
  note_loss_weight: 1.0
  duration_loss_weight: 1.0
  gap_loss_weight: 1.0
  dropout: 0.3

training:
  batch_size: 64
  epochs: 1
  lr: 1e-5
  weight_decay: 0.01
  train_encoder: True

data:
  data_dir: './data/new_dataset'
  max_sequence_length: 200
  output_eos: 1
  use_syllables: False

seed: 42