model:
  dropout: 0.1
  hidden_size: 512

training:
  batch_size: 2000
  epochs: 20
  lr: 1e-5
  weight_decay: 0.01
  note_loss_weight: 1.0
  duration_loss_weight: 1.0
  gap_loss_weight: 1.0

data:
  data_dir: './data/new_dataset_length20'
  max_sequence_length: 21 # include <eos>

seed: 42
out_dir: './runs/RNN'