model:
  dropout: 0.2
  hidden_size: 256
  num_layers: 8

training:
  batch_size: 2000
  epochs: 50
  lr: 1e-3
  weight_decay: 0.01
  note_loss_weight: 1.0
  duration_loss_weight: 1.0
  gap_loss_weight: 1.0
  print_predictions: True # print first eval predictions during training

data:
  data_dir: './data/new_dataset_length20'
  max_sequence_length: 21 # include <eos>

seed: 42
out_dir: './runs/RNN'